# Generated by Django 3.1.7 on 2021-03-31 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Todo Item')),
                ('descr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Todo Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('is_completed', models.BooleanField(verbose_name='Completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
